### PR TITLE
added heapsort.java

### PR DESCRIPTION
**Pull request by Resolution-1**
Please check all that apply.

#### This PR is for:
- [x] Algorithm
- [ ] Cheatsheet
- [ ] Resource
- [ ] Other

#### Programming Language: [python]

- [x] Have you implemented it on your local machine or any online compiler?
- [x] There is the main( ) function to run the program and all the inputs which are being taken are clearly printed on the console or well commented in the file.
- [x] Filename is self-explanatory or there is Readme.md file explaining the necessary details of the algorithm.

### CODE REVIEW

**Comment by Resolution-1** [comment]
added  heapsort algorithm to python sorting algorithm section

**Review by starkblaze01 — CHANGES_REQUESTED** [review]
Hi @Resolution-1 , thanks for the contribution but we already have a contributor adding heap sort in the python earlier [here](https://github.com/starkblaze01/Algorithms-Cheatsheet-Resources/blob/master/Python/Sorting%20Algorithms/heap_sort.py). You can write the same algorithm in any another language in which it is not available here or any another algorithm in the same language.

**Comment by Resolution-1** [comment]
hey @starkblaze01  can you guide me little like how to change this pull request. Like I can change this only to another language or I need  to do another pull request ??

**Review by starkblaze01 — APPROVED** [review]
Thanks for your contribution 🎉

**Pull request merged**
