### PR TITLE
Merge Sorting added

### PR DESCRIPTION
**Pull request by sanchit28**
Please check all that apply.

#### This PR is for:
- [x] Algorithm
- [ ] Cheatsheet
- [ ] Resource
- [ ] Other

#### Programming Language: [Language here]

- [x] Have you implemented it on your local machine or any online compiler?
- [ ] There is the main( ) function to run the program and all the inputs which are being taken are clearly printed on the console or well commented in the file.
- [x] Filename is self-explanatory or there is Readme.md file explaining the necessary details of the algorithm.

### CODE REVIEW

**Review by starkblaze01 — CHANGES_REQUESTED** [review]
Hi, @sanchit28 thanks for your contribution. But merge sort in python is already present [here](https://github.com/starkblaze01/Algorithms-Cheatsheet-Resources/blob/master/Python/Sorting%20Algorithms/merge_sort.py). You can write the same algorithm in any another language in which it is not available here or any another algorithm in the same language.

**Comment by sanchit28** [comment]
I will change that the pull requested I send is for python folder If I change the file with another language is it okay..

**Comment by starkblaze01** [comment]
Yeah, sure. Just cross-check it shouldn't be present in that language already.

**Comment by sanchit28** [comment]
you can check now

**Comment by starkblaze01** [comment]
Hi @sanchit28, this algorithm was also added in the recent contribution [here](https://github.com/starkblaze01/Algorithms-Cheatsheet-Resources/commit/0fe3358586e566322aec406bdc0f778a655dd2c2).

**Review by starkblaze01 — CHANGES_REQUESTED** [review]
Also, make sure the file is in the correct folder. 😄

**Comment by sanchit28** [comment]
May be for that i need to create a new PR

**Pull request closed without merging**
