### PR TITLE
Add script to quick print class attributes

### PR DESCRIPTION
**Pull request by zmcddn**
Please check all that apply.

#### This PR is for:
- [ ] Algorithm
- [x] Cheatsheet
- [ ] Resource
- [ ] Other

#### Programming Language: [Python]

- [x] Have you implemented it on your local machine or any online compiler?
- [ ] There is the main( ) function to run the program and all the inputs which are being taken are clearly printed on the console or well commented in the file.
- [x] Filename is self-explanatory or there is Readme.md file explaining the necessary details of the algorithm.

### CODE REVIEW

**Review by starkblaze01 — CHANGES_REQUESTED** [review]
Hi @zmcddn, Can you remove `Handy_Scripts` file from your PR commit?

**Comment by zmcddn** [comment]
Updated, sry about that. 
Do you mind adding the `hacktoberfest-accepted` label for the hacktoberfest? Thanks

**Review by starkblaze01 — APPROVED** [review]
Thanks for your contribution 🎉

**Comment by starkblaze01** [comment]
Closes #311

**Pull request merged**
