### PR TITLE
Algorithms spelling.

### PR DESCRIPTION
**Pull request by Sandeep-1507**
Please check all that apply.

#### This PR is for:
- [ ] Algorithm
- [ ] Cheatsheet
- [x] Resource
- [x] Other

#### Programming Language: [Language here]

- [ ] Have you implemented it on your local machine or any online compiler?
- [ ] There is the main( ) function to run the program and all the inputs which are being taken are clearly printed on the console or well commented in the file.
- [ ] Filename is self-explanatory or there is Readme.md file explaining the necessary details of the algorithm.

### CODE REVIEW

**Comment by Sandeep-1507** [comment]
Don't judge me on doing such unworthy change,I just found it out so changed it.

**Comment by starkblaze01** [comment]
Hi @Sandeep-1507 
Thanks for the contribution. Even a small contribution in open source is a contribution
But as per the hacktoberfest rules, I won't be able to mark it as Hacktoberfest contribution as it's doesn't pass the quality check

image
Many repositories have been banned and marking it as accepted will lead the for this repository and won't allow other contributors to make quality contribution.

**Review by starkblaze01 — COMMENTED** [review]
LGTM, but not hacktoberfest-accepted

**Comment by Sandeep-1507** [comment]
@starkblaze01 No Problems by me:)
I just found out so mentioned I also don't want to win hacktoberfest without having the worth.

**Pull request merged**
