### PR TITLE
Added longest_common_subsequence.cpp

### PR DESCRIPTION
**Pull request by rudrakshi99**
Please check all that apply.

#### This PR is for:
- [x] Algorithm
- [ ] Cheatsheet
- [ ] Resource
- [ ] Other

#### Programming Language: CPP

- [x] Have you implemented it on your local machine or any online compiler?
- [x] There is the main( ) function to run the program and all the inputs which are being taken are clearly printed on the console or well commented in the file.
- [x] Filename is self-explanatory or there is Readme.md file explaining the necessary details of the algorithm.

### CODE REVIEW

**Review by starkblaze01 — CHANGES_REQUESTED** [review]
Hi @rudrakshi99, Can you please verify the output of the code? Because it is returning `Segmentation fault` in online compilers. Please do attach a screenshot in case the output is working fine on your system.

**Comment by rudrakshi99** [comment]
@starkblaze01, I  have resolved the Segmentation fault. Please review this.

**Review by starkblaze01 — APPROVED** [review]
Great, thanks for your contribution 🎉

**Comment by rudrakshi99** [comment]
@starkblaze01 Can you also label this pull request as "hacktoberfest-accepted"?

**Comment by starkblaze01** [comment]
Hi @rudrakshi99, according to Hactoberfest rule the only label that they keep track of are `invalid`, `spam` in case the PR do not meet the Contributing Guidelines, and `ready-for-review` in case it is a valid PR but not merged yet so that it will be counted in Hacktoberfest contribution. 
If you go to the link `https://hacktoberfest.digitalocean.com/profile`, you can see there will 14 days maturing period on the PR you have created which will give time for project Maintainer to check the validity of PR. After 14 if it is not marked as spam it will be automatically counted as your valid contribution. Earlier it was 7 days but due to lots of spam contribution this year, it is increased to 14 days. I hope this helps.

**Comment by rudrakshi99** [comment]
Ok, thank you.

**Pull request merged**
