### PR TITLE
binary search implementation in cpp

### PR DESCRIPTION
**Pull request by Maheejaiswal**
Please check all that apply.

#### This PR is for:
- [ ] Algorithm

#### Programming Language: [cpp]

- [ ] Have you implemented it on your local machine or any online compiler?
- [ ] There is the main( ) function to run the program and all the inputs which are being taken are clearly printed on the console or well commented in the file.
- [ ] Filename is self-explanatory or there is Readme.md file explaining the necessary details of the algorithm.

### CODE REVIEW

**Review by starkblaze01 — APPROVED** [review]
Thanks for your contribution 🎉

**Comment by Maheejaiswal** [comment]
please do me a favor of adding "hacktoberfest-accepted" label to it.

**Comment by starkblaze01** [comment]
Hi @Maheejaiswal, hacktoberfest only checks for `invalid` tag. You can see that in your hacktoberfest dashboard this PR is mentioned with a start cooldown of 7 days. They check how many README updates, trailing spaces, and another similar kind of commits were done. After 7 days you could see this PR being marked approved.

**Comment by Maheejaiswal** [comment]
Thank you @starkblaze01. They updated some rules I guess and the review period is of 14 days now.

**Comment by starkblaze01** [comment]
Oh right, they changed that after it was started.

**Pull request merged**
